### ISSUE TITLE
Required packages not in setup.py

### ISSUE THREAD

**Issue by eric-czech** [fastlmm/bed-reader#1]
Hey @CarlKCarlK, I see only numpy is in the setup.py dependency list: https://github.com/fastlmm/bed-reader/blob/a775a57060ec39c70531ca09f7b5dbe9a683b34f/setup.py#L149

But the requirements.txt has several others: https://github.com/fastlmm/bed-reader/blob/a775a57060ec39c70531ca09f7b5dbe9a683b34f/requirements.txt#L1-L5

`pooch` being missing is currently breaking the [sgkit-plink build](https://github.com/pystatgen/sgkit-plink/pull/30/checks?check_run_id=1068392010) with:

```
ImportError while importing test module '/home/runner/work/sgkit-plink/sgkit-plink/sgkit_plink/tests/test_pysnptools.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
sgkit_plink/__init__.py:1: in <module>
    from .pysnptools import read_plink  # noqa: F401
sgkit_plink/pysnptools.py:8: in <module>
    from bed_reader import open_bed
/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/bed_reader/__init__.py:2: in <module>
    from bed_reader._sample_data import sample_file, tmp_path
/opt/hostedtoolcache/Python/3.8.5/x64/lib/python3.8/site-packages/bed_reader/_sample_data.py:7: in <module>
    import pooch
E   ModuleNotFoundError: No module named 'pooch'
```

I'm guessing `_sample_data.py` isn't critical for downstream usage so is it possible to only import that when a function in that module is called instead?

**Comment by CarlKCarlK** [comment]
I’ll work on a new alpha release this afternoon that will fix that.

The requirements.txt will be something like:

numpy
pandas
dataclass
pooch

**Comment by CarlKCarlK** [comment]
Fixed with https://pypi.org/project/bed-reader/0.0.5a0/
