### ISSUE TITLE
ValueError: File 'example.fam' is not in the registry.

### ISSUE THREAD

**Issue by bill-95** [fastlmm/bed-reader#10]
I run this:

`file_name = sample_file("example.bed")`

and get:

`ValueError: File 'example.fam' is not in the registry.`

I set the `BED_READER_DATA_DIR` to the directory where the .bed file is per docstring. But no bueno.

```
Signature: sample_file(filepath: Union[str, pathlib.Path]) -> str
Docstring:
Retrieve a sample .bed file. (Also retrieves associated .fam and .bim files).

Parameters
----------
filepath
    Name of the sample .bed file.

Returns
-------
str
    Local name of sample .bed file.


By default this function puts files under the user's cache directory.
Override this by setting
the `BED_READER_DATA_DIR` environment variable.
```

**Comment by CarlKCarlK** [comment]
Bill,

Thanks for using Bed-Reader!

Are you trying to download a bed-reaader sample file or to read a file of your own?
Can you show me what you set BED_READER_DATA_DIR to?

Thanks,
Carl


Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team<https://fastlmm.github.io/>
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/

Join the FaST-LMM user discussion and announcement list via ***@***.***?subject=Subscribe> (or use web sign up<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0>)
From: bill-95 ***@***.***>
Sent: Tuesday, November 22, 2022 12:40 PM
To: fastlmm/bed-reader ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/bed-reader] ValueError: File 'example.fam' is not in the registry. (Issue #10)
Importance: High


I run this:

file_name = sample_file("example.bed")

and get:

ValueError: File 'example.fam' is not in the registry.

I set the BED_READER_DATA_DIR to the directory where the .bed file is per docstring. But no bueno.

Signature: sample_file(filepath: Union[str, pathlib.Path]) -> str

Docstring:

Retrieve a sample .bed file. (Also retrieves associated .fam and .bim files).



Parameters

----------

filepath

    Name of the sample .bed file.



Returns

-------

str

    Local name of sample .bed file.





By default this function puts files under the user's cache directory.

Override this by setting

the `BED_READER_DATA_DIR` environment variable.

-

**Comment by bill-95** [comment]
I misunderstood the usage. I thought I was supposed to point the `BED_READER_DATA_DIR` to where I put my local .bed files.

I have figured out how to load my files. It works great, thanks!

**Comment by CarlKCarlK** [comment]
Bill

Excellent! Thanks again for using bed-reader.


  *   Carl
