### ISSUE TITLE
Python dependencies no longer install with latest Maturin release. 

### ISSUE THREAD

**Issue by bradday4** [fastlmm/bed-reader#11]
Hello. Just wanted to start off by saying this project is great. I'm using it as reference for my own projects.

I noticed that when I first went to `pip install bed-reader` from pypi as per the docs, I immediately got an import error `ModuleNotFoundError` for numpy when trying to import the `bed_reader` module.  I decided to build the project locally to see what the issue was.
As I was building with Maturin I saw the following warning pop up. 
![image](https://user-images.githubusercontent.com/24538279/216506465-8eac4270-f804-437a-b5e4-521857ad3079.png)
As of maturin v-0.14.0 placing the python dependencies in `cargo.toml` are no longer supported.
I moved the dependencies into pyproject.toml and everything was able to build correctly on my machine.
I tried this with the maturin docker image as well as locally with maturin in my virtualenv.

The Docker image your build system relies on ...
https://github.com/fastlmm/bed-reader/blob/46ece2e6efd1fb8f5a9335fd8b3ef7a3d711b9fa/.github/workflows/ci.yml#L69
... will pull the latest image which is currently v-0.14.2

![image](https://user-images.githubusercontent.com/24538279/216507138-ddc2f010-3cdd-4c8a-8b39-ace25f0b6b00.png)

Depending on your needs I guess there are two approaches. 
1. move metadata fields from `cargo.toml` -> `pyproject.toml`
2. pin `ghcr.io/pyo3/maturin` docker image to an older build

I'd be in favor of approach 1 but there may some other reasons i'm unaware of to do 2.
Hope this report helps.

**Comment by bradday4** [comment]
Quick follow up. Here's the [PR](https://github.com/PyO3/maturin/pull/1200) from Maturin indicating their removal of support for python package metadata in Cargo.toml

**Comment by CarlKCarlK** [comment]
Brad,

Thanks for your note. I'll try to fix it on the next version of bed-reader.

In pyprojects.toml<https://github.com/fastlmm/bed-reader/blob/master/pyproject.toml>, I currently have these lines:
[build-system]
requires = ["maturin==0.12.5"]
build-backend = "maturin"

but I don't remember exactly that that is supposed to do.

Yours,
Carl


Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team<https://fastlmm.github.io/>
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/

Join the FaST-LMM user discussion and announcement list via ***@***.***?subject=Subscribe> (or use web sign up<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0>)

**Comment by CarlKCarlK** [comment]
I think this now all updated and fixed.
