### ISSUE TITLE
Build macOS arm64 wheels

### ISSUE THREAD

**Issue by tomwhite** [fastlmm/bed-reader#13]
It would be great to have wheels for Mac Silicon.

Not sure how easy that is to add to the build system, but I wonder if https://github.com/PyO3/maturin-action might be helpful.

**Comment by CarlKCarlK** [comment]
Good idea!. I'm away for a week but will look at this when I get back.
________________________________
From: Tom White ***@***.***>
Sent: Wednesday, May 10, 2023 2:16:25 AM
To: fastlmm/bed-reader ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/bed-reader] Build macOS arm64 wheels (Issue #13)


It would be great to have wheels for Mac Silicon.

Not sure how easy that is to add to the build system, but I wonder if https://github.com/PyO3/maturin-action might be helpful.

**Comment by CarlKCarlK** [comment]
Done! (This is for pip/PyPi. I don't know what to do about conda.)

**Comment by tomwhite** [comment]
I just verified that they worked on my machine - thank you very much @CarlKCarlK!
