### ISSUE TITLE
Add support for Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [fastlmm/bed-reader#2]
Python 3.9 was released on October 5, 2020. It seems the wheels are missing for Python 3.9. This causes issues in sgkit project which has this module as dependency.

https://github.com/aktech/sgkit/runs/1225522394

**Comment by CarlKCarlK** [comment]
Excellent suggestion.

Status so far: When I try to add Python 3.9 support, Windows works, but MacOS and Linux fail.

For Mac, I think we need to wait for a NumPy wheel for CPython 3.9 (see https://github.com/numpy/numpy/issues/17482)
For Linux, travis-ci is timing out:

**Comment by CarlKCarlK** [comment]
(I conferred with @Horta.) When NumPy & Pandas have wheels for Linux for Python 3.9, I'll create one for Bed-Reader, too.

**Comment by CarlKCarlK** [comment]
I've added support for Python 3.9. Thanks for your suggestion.
