### ISSUE TITLE
pip install bed-reader[samples,sparse] zsh: no matches found

### ISSUE THREAD

**Issue by chenghongdeng** [fastlmm/bed-reader#23]
Hi, 

I am trying to install the bed-reader on my Mac. When I try to install with command: 
`pip install bed-reader`
I am able to install the package. 

However, when I try to import the bed6 file into python. The command I use: 
```
import numpy as np
from bed_reader import open_bed, sample_file

file_name = sample_file("hg38.RefSeq.reduced.mRNA.CDS.bed6")
bed = open_bed(file_name)
```

The error message I got: 
>ImportError: The function sample_file() requires pooch. Install it with 'pip install --upgrade bed-reader[sample]'.

Thus, I am trying to install the bed-reader with command: 
`pip install bed-reader[samples,sparse]`

I start to get the error message: 
>zsh: no matches found: bed-reader[samples,sparse]

I am not sure how to solve this problem. I am appreciate if you could help with it. Thank you

**Comment by CarlKCarlK** [comment]
Thanks for trying bed-reader!

Please try:

```
import numpy as np
from bed_reader import open_bed

bed = open_bed("hg38.RefSeq.reduced.mRNA.CDS.bed6")
```


I've not seen *.bed6. If it is PLINK BED 1.9 format, the above should work. If it is some other format, then bed-reader cannot read it.

Yours,
Carl
