### ISSUE TITLE
[Bug] in _open_bed.py: File handler not closed

### ISSUE THREAD

**Issue by r1cheu** [fastlmm/bed-reader#28]
Hi! I'm using the bed_reader library with my project and encountered a minor bug in _open_bed.py. The file handler is not closed properly at line 1230, which raises an error when using pytest.

The error message is as follows:
```
                   pytest.PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>

                   Traceback (most recent call last):
                     File "/home/rlchen/.miniforge3/envs/phenx/lib/python3.12/site-packages/bed_reader/_open_bed.py", line 1230, in _count
                       count = _rawincount(open(location, "rb"))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                   ResourceWarning: unclosed file <_io.BufferedReadername='/home/rlchen/.cache/bed_reader/small.bim'>
```
Simply using the with context manager could help resolve this issue.

**Comment by CarlKCarlK** [comment]
Thanks for using BedReader and thanks for finding, figuring out, and reporting this bug.

-- Carl

________________________________
From: r1cheu ***@***.***>
Sent: Tuesday, August 6, 2024 11:38:06 PM
To: fastlmm/bed-reader ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fastlmm/bed-reader] [Bug] in _open_bed.py: File handler not closed (Issue #28)


Hi! I'm using the bed_reader library with my project and encountered a minor bug in _open_bed.py. The file handler is not closed properly at line 1230, which raises an error when using pytest.

The error message is as follows:

                   pytest.PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>

                   Traceback (most recent call last):
                     File "/home/rlchen/.miniforge3/envs/phenx/lib/python3.12/site-packages/bed_reader/_open_bed.py", line 1230, in _count
                       count = _rawincount(open(location, "rb"))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                   ResourceWarning: unclosed file <_io.BufferedReadername='/home/rlchen/.cache/bed_reader/small.bim'>


Simply using the with context manager could help resolve this issue.
