### ISSUE TITLE
unable to install with pip

### ISSUE THREAD

**Issue by remomomo** [fastlmm/bed-reader#3]
I'm facing issues installing fastlmm because of bed-reader

`pip install bed-reader`

```
ERROR: Could not find a version that satisfies the requirement bed-reader (from versions: none)
ERROR: No matching distribution found for bed-reader
```

same issue when trying to install fastlmm

pip 20.2.4

**Comment by remomomo** [comment]
ahh I hadn't seen the update to python 3.9, it works with python 3.8

**Comment by CarlKCarlK** [comment]
Thanks for your interest in FaST-LMM and for figuring out your problem.

(It looks like NumPy has been updated for 3.9 and – maybe – Anaconda. If so, I’ll start updating our packages to 3.9.)


Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team<https://fastlmm.github.io/>
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/

Join the FaST-LMM user discussion and announcement list via email<mailto:fastlmm-user-join@python.org?subject=Subscribe> (or use web sign up<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0>)

**Comment by CarlKCarlK** [comment]
The Python 3.9 releases of Bed-Reader (and PySnpTools) are now available.
